### ISSUE TITLE
crash opening an image from within ObscuraCam, cannot write

### ISSUE THREAD

**Issue by klic** [guardianproject/ObscuraCam#140]
I'm now on LOS 18.1 build 20210908 (I'm not sure when it started, but I'm sure it already worked on LOS18.1)
Trying to open an image from the dialog results in

```
9-09 08:03:22.073  1305  4042 I ActivityTaskManager: START u0 {cmp=org.witness.sscphase1/org.witness.obscuracam.ui.AlbumsActivity} from uid 10142
09-09 08:03:22.209  1305  1511 I ActivityTaskManager: Displayed org.witness.sscphase1/org.witness.obscuracam.ui.AlbumsActivity: +135ms
09-09 08:03:28.023  1305  3651 I ActivityTaskManager: START u0 {dat=content://com.android.providers.media.documents/document/image:42867 cmp=org.witness.sscphase1/org.witness.obscuracam.ui.ImageEditor} from uid 10142
09-09 08:03:28.174 14448 14448 D AndroidRuntime: Shutting down VM
09-09 08:03:28.175 14448 14448 E AndroidRuntime: FATAL EXCEPTION: main
09-09 08:03:28.175 14448 14448 E AndroidRuntime: Process: org.witness.sscphase1, PID: 14448
09-09 08:03:28.175 14448 14448 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.witness.sscphase1/org.witness.obscuracam.ui.ImageEditor}: java.lang.NullPointerException
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: Caused by: java.lang.NullPointerException
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at java.io.File.<init>(File.java:283)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at org.witness.obscuracam.ui.ImageEditor.pullPathFromUri(ImageEditor.java:1711)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at org.witness.obscuracam.ui.ImageEditor.onCreate(ImageEditor.java:397)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7994)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7978)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
09-09 08:03:28.175 14448 14448 E AndroidRuntime: 	... 11 more
09-09 08:03:28.189  1305  5331 W ActivityTaskManager:   Force finishing activity org.witness.sscphase1/org.witness.obscuracam.ui.ImageEditor
09-09 08:03:28.366  1305  5933 I WindowManager: WIN DEATH: Window{bcb876f u0 org.witness.sscphase1/org.witness.obscuracam.ui.AlbumsActivity}

```

Also, trying to save an image results in EACCESS, it can't write into Pictures any longer.

**Comment by cm-mc** [comment]
Same here (A10/OneUI 2.5, magisk rooted). Also can't save pics taken & edited from the app; stuck "Saving..." forever (permissions granted).
